// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gpuKnowledgeBase: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the root of the docs folder
    },
  ],
};
// const sidebars = {
//   gpuKnowledgeBase: [
//     // ── 01: FOUNDATIONS ──────────────────────────────────────────────────────
//     {
//       type: 'category',
//       label: '01 · Foundations',
//       collapsible: true,
//       collapsed: false,
//       items: [
//         'intro',
//         'gpu-vs-cpu',
//         'cuda-programming-model',
//       ],
//     },

//     // ── 02: MEMORY HIERARCHY ─────────────────────────────────────────────────
//     {
//       type: 'category',
//       label: '02 · Memory Hierarchy',
//       collapsible: true,
//       collapsed: false,
//       items: [
//         'memory-overview',
//         'registers',
//         'shared-memory',
//         'global-memory',
//         'l1-l2-cache',
//       ],
//     },

//     // ── 03: EXECUTION MODEL ───────────────────────────────────────────────────
//     {
//       type: 'category',
//       label: '03 · Execution Model',
//       collapsible: true,
//       collapsed: false,
//       items: [
//         'sm-architecture',
//         'warp-execution',
//         'occupancy-model',
//         'synchronization',
//       ],
//     },

//     // ── 04: ARCHITECTURE DEEP DIVES ───────────────────────────────────────────
//     {
//       type: 'category',
//       label: '04 · Architecture Deep Dives',
//       collapsible: true,
//       collapsed: false,
//       items: [
//         {
//           type: 'category',
//           label: 'Volta (SM 7.0)',
//           items: ['volta'],
//         },
//         {
//           type: 'category',
//           label: 'Turing (SM 7.5)',
//           items: ['turing'],
//         },
//         {
//           type: 'category',
//           label: 'Ampere (SM 8.x)',
//           items: ['ampere'],
//         },
//         {
//           type: 'category',
//           label: 'Ada Lovelace (SM 8.9)',
//           items: ['ada-lovelace'],
//         },
//         {
//           type: 'category',
//           label: 'Hopper (SM 9.0)',
//           items: ['hopper'],
//         },
//         {
//           type: 'category',
//           label: 'Blackwell (SM 10.0)',
//           items: ['blackwell'],
//         },
//       ],
//     },

//     // ── 05: OPTIMIZATION TECHNIQUES ───────────────────────────────────────────
//     {
//       type: 'category',
//       label: '05 · Optimization Techniques',
//       collapsible: true,
//       collapsed: false,
//       items: [
//         {
//           type: 'category',
//           label: 'Occupancy',
//           items: ['occupancy-optimization'],
//         },
//         {
//           type: 'category',
//           label: 'Shared Memory & Bank Conflicts',
//           items: ['shared-memory-bank-conflicts'],
//         },
//         {
//           type: 'category',
//           label: 'Warp Divergence',
//           items: ['warp-divergence'],
//         },
//         {
//           type: 'category',
//           label: 'Tensor Cores',
//           items: ['tensor-core-programming'],
//         },
//         {
//           type: 'category',
//           label: 'PTX & SASS',
//           items: ['ptx-sass-basics'],
//         },
//       ],
//     },
//   ],
// };

module.exports = sidebars;
